- hosts: all
  vars:
    home: "{{ansible_env.HOME}}"
    golangVersion: "1.10" 
    nodeVersion: "v8.11.2-linux-x64"
    goTarballUrl: "https://dl.google.com/go/go1.10.2.linux-amd64.tar.gz"
    nodeTarballUrl: "https://nodejs.org/dist/v8.11.2/node-v8.11.2-linux-x64.tar.xz"
  tasks:
    - name: Download tarball and unpack
      unarchive:
        src: "{{goTarballUrl}}"
        remote_src: yes
        dest: "{{home}}/"
    - name: Add GOROOT 
      lineinfile:
        path: "{{home}}/.bash_profile"
        regexp: "^export GOROOT="
        line: "export GOROOT={{home}}/go"
        create: true
    - name: Add GOROOT/bin into path
      lineinfile:
        path: "{{home}}/.bash_profile"
        line: "export PATH={{home}}/go/bin:$PATH"
        create: true
    - name: Download tarball and unpack
      unarchive:
        src: "{{nodeTarballUrl}}"
        remote_src: yes
        dest: "{{home}}/"
    - name: Add node binaries into PATH
      lineinfile:
        path: "{{home}}/.bash_profile"
        line: "export PATH={{home}}/node-{{nodeVersion}}/bin:$PATH"
        create: true
    - name: add additional repos
      become: true
      yum:
        name: "{{item}}"
      when: ansible_os_family == "RedHat"
      with_items:
        - epel-release
        - centos-release-scl
    - name: add additional packages
      become: true
      yum:
        name: "{{item}}"
      with_items:
        - autoconf
        - automake
        - ganglia-devel
        - gcc
        - iptables-devel
        - jave-1.8.0-openjdk
        - jave-1.8.0-openjdk-devel
        - libatamsmart-devel
        - libcurl-devel
        - libdbi-devel
        - libesmtp-devel
        - libmemcached-devel
        - libmodbus-devel
        - liboping
        - libpcap-devel
        - libuuid-devel
        - libvirt-devel
        - libxml2-devel
        - lm_sensors-devel
        - lua-devel
        - lvm2-devel
        - make
        - memcached-devel
        - mysql-devel
        - paho-c-devel
        - patch
        - postgresql-devel
        - python27-python-devel
        - python27-python-pip
        - python27-python-virtualenv
        - rabbitmq-devel
        - rrdtool-devel
        - xfsprogs-devel
        - yajl-devel
      when: ansible_os_family == "RedHat"
